language: python
python: "3.6.5"
before_install:
  - python --version
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - echo "running tests"
after_success:
  - coveralls
notifications:
  email: false
